[package]
name = "input-linux-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
input-linux = "0.7.1"
nonblock = "0.2.0"

[patch.crates-io]
#nonblock = { path = "../nonblock-rs" }
nonblock = { git = "https://github.com/perlindgren/nonblock-rs" }
