[package]
name = "input-linux-tools"
version = "0.1.0"
edition = "2021"


[dependencies]
input-linux = "0.7.1"
libc = "0.2.161"
log = "0.4.22"
serde = { version = "1.0.211", features = ["derive"] }

[dev-dependencies]
winit = "0.30.5"
